
# Busines Function Codes
BANK_TRANSFER = 'BTR'
CHECK_SAME_DAY_SETTLEMENT = 'CKS'
CUSTOMER_TRANSFER_PLUS = 'CTP'
CUSTOMER_TRANSFER = 'CTR'
DEPOSITY_TO_SENDERS_ACCOUNT = 'DEP'
BANK_TO_BANK_DRAWDOWN_REQUEST = 'DRB'
CUSTOMER_OR_CORPORATE_DRAWDOWN_REQUEST = 'DRC'
DRAWDOWN_PAYMENT = 'DRW'
FED_FUNDS_RETURNED = 'FFR'
FED_FUNDS_SOLD = 'FFS'
SERVICE_MESSAGE = 'SVC'

# ID Codes
SWIFT_BANK_IDENTIFIER_CODE = 'B'
CHIPS_PARTICIPANT = 'C'
DEMAND_DEPOSIT_ACCOUNT_NUM = 'D'
FED_ROUTING_NUMBER = 'F'
SWIFT_BIC_BEI = 'T'
CHIPS_IDENTIFIER = 'U'
PASSPORT_NUMBER = '1'
TAX_IDENTIFICATION_NUMBER = '2'
DRIVERS_LICENSE_NUMBER = '3'
ALIEN_REGISTRATION_NUMBER = '4'
CORPORATE_IDENTIFICATION = '5'
OTHER_IDENTIFICATION = '9'


# Type Code Reference
FUNDS_TRANSFER = '10'
FOREIGN_TRANSFER = '15'
SETTLEMENT_TRANSFER = '16'

# Subtype Code Reference
BASIC_FUNDS_TRANSFER = '00'
REQUEST_FOR_REVERSAL = '01'
REVERSAL_OF_TRANSFER = '02'
REQUEST_FOR_REVERSAL_PRIOR_DAY = '07'
REQUEST_OF_REVERSAL_PRIOR_DAY = '08'
REQUEST_FOR_CREDIT = '31'
FUNDS_TRANSFER_REQUEST_FOR_CREDIT = '32'
REFUSAL_TO_HONOR_REQUEST_FOR_CREDIT = '33'
SERVICE_MESSAGE = '90'


# Advice codes
HOLD = 'HLD'
LETTER = 'LTR'
PHONE = 'PHN'
TELEX = 'TLX'
WIRE = 'WRE'

# Address Types
COMPLETE_POST_ADDRESS = 'ADDR'
BUSINESS_ADDRESS = 'BIZZ'
DELIVER_ADDRESS = 'DLVY'
HOME_ADDRESS = 'HOME'
MAIL_ADDRESS = 'MLTO'
POST_OFFICE_BOX = 'PBOX'